apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-server-test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-server-test
  template:
    metadata:
      labels:
        app: web-server-test
    spec:
      nodeSelector:
        type: web
      containers:
      - name: nginx
        image: leedowning113/web-server-test:v3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "300m"
            memory: "256Mi"
        volumeMounts:             # 추가
        - name: web-log
          mountPath: /data
      volumes:                     # 추가 
      - name: web-log
        persistentVolumeClaim:
          claimName: web-log-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: web-server-test-svc
spec:
  type: NodePort
  selector:
    app: web-server-test
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080

